<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8pNB3TH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8pNB3TH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8pNB3TH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8pNB3TH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8pNB3TH\App_KernelDevDebugContainer([
    'container.build_hash' => '8pNB3TH',
    'container.build_id' => '3de13a5e',
    'container.build_time' => 1698316645,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8pNB3TH');
